// $Id: OntologySearchEvent.as 38 2011-03-18 05:41:28Z taruss2000@gmail.com $
//
//  $Date: 2011-03-17 22:41:28 -0700 (Thu, 17 Mar 2011) $
//  $Revision: 38 $
//
package edu.isi.bmkeg.kefed.ontology {
	import flash.events.Event;
	
	import mx.collections.ArrayCollection;

	/** Class for events generated by using web services to
	 *  search for ontology terms.
	 * 
	 * @author University of Southern California
	 * @date $Date: 2011-03-17 22:41:28 -0700 (Thu, 17 Mar 2011) $
	 * @version $Revision: 38 $
	 */
	public class OntologySearchEvent extends Event {
		public static const FIND_ONTOLOGY_TERMS:String = "find-ontology-terms";
		public static const LIST_ONTOLOGIES:String = "list-ontologies";
		public static const SET_ONTOLOGY_IDS:String = "set-ontology-ids";
		public static const ADD_ONTOLOGY_IDS:String = "add-ontology-ids";
		
		public var searchResults:ArrayCollection;
		
		public function OntologySearchEvent(type:String, results:ArrayCollection) {
			super(type);
			this.searchResults = results;
		}		
	}
}